package com.idworx.lisa.features.personality.dialogue

import com.idworx.lisa.features.personality.model.DialogueCategory
import com.idworx.lisa.features.personality.model.LisaDialogue
import com.idworx.lisa.features.personality.model.MilestoneType

interface DialogueCatalog {
    fun all(locale: String = "en"): List<LisaDialogue>
    fun forCategory(category: DialogueCategory, locale: String = "en"): List<LisaDialogue>
    fun forMilestone(type: MilestoneType, locale: String = "en"): List<LisaDialogue>
}

class DefaultDialogueCatalogProvider : DialogueCatalogProvider {
    override fun catalog(locale: String): LisaDialogueProvider =
        DefaultDialogueCatalog.asProvider(locale)
}

object DefaultDialogueCatalog : DialogueCatalog {

    private val entries: List<LisaDialogue> = buildCatalog()

    override fun all(locale: String): List<LisaDialogue> =
        entries.filter { it.locale == locale }

    override fun forCategory(category: DialogueCategory, locale: String): List<LisaDialogue> =
        entries.filter { it.category == category && it.locale == locale }

    override fun forMilestone(type: MilestoneType, locale: String): List<LisaDialogue> =
        entries.filter { it.milestoneType == type && it.locale == locale }

    fun asProvider(locale: String = "en"): LisaDialogueProvider = object : LisaDialogueProvider {
        override fun dialoguesFor(category: DialogueCategory, locale: String): List<LisaDialogue> =
            forCategory(category, locale)

        override fun allDialogues(locale: String): List<LisaDialogue> = all(locale)
    }

    private fun d(
        id: String,
        text: String,
        category: DialogueCategory,
        weight: Int = 1,
        milestone: MilestoneType? = null,
        tags: Set<String> = emptySet()
    ) = LisaDialogue(
        id = id,
        text = text,
        category = category,
        locale = "en",
        weight = weight,
        milestoneType = milestone,
        contextTags = tags
    )

    private fun buildCatalog(): List<LisaDialogue> = listOf(
        // Greetings — first launch / first conversation (Zero-Touch Principle)
        d("greet_first_01", "Hello.", DialogueCategory.Greeting, tags = setOf("first_launch", "first_conversation")),
        d("greet_first_02", "My name is Lisa.", DialogueCategory.Greeting, tags = setOf("first_launch", "first_conversation")),
        d("greet_first_03", "I'm here to help you communicate using your eyes.", DialogueCategory.Greeting, tags = setOf("first_launch", "first_conversation")),
        d("greet_first_04", "Whether you're using Lisa yourself, or helping someone you care about, I'll guide you every step of the way.", DialogueCategory.Greeting, tags = setOf("first_launch", "first_conversation")),
        d("greet_first_05", "There is no rush.", DialogueCategory.Greeting, tags = setOf("first_launch", "first_conversation")),
        d("greet_first_06", "We'll learn together.", DialogueCategory.Greeting, tags = setOf("first_launch", "first_conversation")),
        d("greet_first_07", "If you cannot move your hands, that's perfectly okay.", DialogueCategory.Greeting, tags = setOf("first_launch", "first_conversation")),
        d("greet_first_08", "Everything we're going to do can be done using only your eyes.", DialogueCategory.Greeting, tags = setOf("first_launch", "first_conversation")),
        // Greetings — returning
        d("greet_return_01", "Welcome back.", DialogueCategory.Greeting, tags = setOf("returning")),
        d("greet_return_02", "Last time we learned together.", DialogueCategory.Greeting, tags = setOf("returning")),
        d("greet_return_03", "Would you like to continue where we left off?", DialogueCategory.Greeting, tags = setOf("returning")),
        d("greet_return_04", "I'm happy you're here.", DialogueCategory.Greeting, tags = setOf("returning")),
        d("greet_return_05", "We can keep learning together.", DialogueCategory.Greeting, tags = setOf("returning")),
        d("greet_return_06", "I'm here with you.", DialogueCategory.Greeting, tags = setOf("returning")),
        // Welcome
        d("welcome_01", "Welcome.", DialogueCategory.Welcome),
        d("welcome_02", "I'm glad you're here.", DialogueCategory.Welcome),
        d("welcome_03", "Let's take this one step at a time.", DialogueCategory.Welcome),
        // Instructions
        d("instr_01", "Let's start with something simple.", DialogueCategory.Instruction),
        d("instr_02", "Take your time.", DialogueCategory.Instruction),
        d("instr_03", "When you're ready, try the sequence shown on the screen.", DialogueCategory.Instruction),
        d("instr_04", "Now we'll practice a phrase you may use often.", DialogueCategory.Instruction),
        d("instr_05", "Let's practice opening the menu.", DialogueCategory.Instruction),
        d("instr_06", "Now let's go back together.", DialogueCategory.Instruction),
        d("instr_07", "We can repeat this as many times as you need.", DialogueCategory.Instruction),
        d("instr_08", "Let's slow things down.", DialogueCategory.Instruction, tags = setOf("struggling")),
        // Encouragement
        d("enc_01", "Excellent.", DialogueCategory.Encouragement),
        d("enc_02", "Wonderful.", DialogueCategory.Encouragement),
        d("enc_03", "You're doing great.", DialogueCategory.Encouragement),
        d("enc_04", "Nicely done.", DialogueCategory.Encouragement),
        d("enc_05", "That was fantastic.", DialogueCategory.Encouragement),
        d("enc_06", "You're improving every time.", DialogueCategory.Encouragement),
        d("enc_07", "You're making wonderful progress.", DialogueCategory.Encouragement),
        d("enc_08", "You're getting more confident.", DialogueCategory.Encouragement),
        d("enc_09", "Keep going.", DialogueCategory.Encouragement),
        d("enc_10", "That was really good.", DialogueCategory.Encouragement),
        d("enc_11", "You did that beautifully.", DialogueCategory.Encouragement),
        d("enc_12", "I'm proud of your progress.", DialogueCategory.Encouragement),
        d("enc_13", "You're learning this step by step.", DialogueCategory.Encouragement),
        d("enc_14", "That was a strong attempt.", DialogueCategory.Encouragement),
        d("enc_15", "You handled that well.", DialogueCategory.Encouragement),
        // Comfort
        d("com_01", "That's okay.", DialogueCategory.Comfort),
        d("com_02", "Take your time.", DialogueCategory.Comfort),
        d("com_03", "No rush.", DialogueCategory.Comfort),
        d("com_04", "We'll try together.", DialogueCategory.Comfort),
        d("com_05", "You're doing well.", DialogueCategory.Comfort),
        d("com_06", "Let's slow things down.", DialogueCategory.Comfort),
        d("com_07", "Every attempt helps us learn.", DialogueCategory.Comfort),
        d("com_08", "We'll keep practicing.", DialogueCategory.Comfort),
        d("com_09", "There is no need to hurry.", DialogueCategory.Comfort),
        d("com_10", "We can repeat this as many times as you need.", DialogueCategory.Comfort),
        d("com_11", "I'm ready whenever you are.", DialogueCategory.Comfort),
        d("com_12", "Let's try again gently.", DialogueCategory.Comfort),
        d("com_13", "You're still making progress.", DialogueCategory.Comfort),
        d("com_14", "We can make this easier if you need.", DialogueCategory.Comfort),
        d("com_15", "We can slow things down if you'd like.", DialogueCategory.Comfort),
        // Waiting
        d("wait_01", "Take your time.", DialogueCategory.Waiting),
        d("wait_02", "I'm ready whenever you are.", DialogueCategory.Waiting),
        d("wait_03", "There's no rush.", DialogueCategory.Waiting),
        d("wait_04", "We'll continue when you're ready.", DialogueCategory.Waiting),
        d("wait_05", "You can begin when you feel ready.", DialogueCategory.Waiting),
        d("wait_06", "I'll wait with you.", DialogueCategory.Waiting),
        d("wait_07", "I'll wait until you're ready.", DialogueCategory.Waiting, tags = setOf("zero_touch")),
        // Gentle missed-blink (Zero-Touch — never blame the user)
        d("ztp_miss_01", "I think I missed that blink.", DialogueCategory.Comfort, tags = setOf("zero_touch")),
        d("ztp_miss_02", "Let's try once more together.", DialogueCategory.Comfort, tags = setOf("zero_touch")),
        d("ztp_miss_03", "That's alright.", DialogueCategory.Comfort, tags = setOf("zero_touch")),
        d("ztp_miss_04", "We'll keep trying together.", DialogueCategory.Comfort, tags = setOf("zero_touch")),
        // First phrase success
        d("ztp_first_01", "Wonderful!", DialogueCategory.MilestoneCelebration, tags = setOf("zero_touch", "first_phrase")),
        d("ztp_first_02", "You did it!", DialogueCategory.MilestoneCelebration, tags = setOf("zero_touch", "first_phrase")),
        d("ztp_first_03", "You've just spoken your very first word using Lisa.", DialogueCategory.MilestoneCelebration, tags = setOf("zero_touch", "first_phrase")),
        // Navigation
        d("nav_01", "Now I'll show you how to move around Lisa.", DialogueCategory.NavigationGuidance),
        d("nav_02", "Let's open the menu together.", DialogueCategory.NavigationGuidance),
        d("nav_03", "Good. Now let's return to the previous screen.", DialogueCategory.NavigationGuidance),
        d("nav_04", "Let's open Quick Phrases.", DialogueCategory.NavigationGuidance),
        d("nav_05", "This is where you can find messages you may use often.", DialogueCategory.NavigationGuidance),
        d("nav_06", "Now let's practice emergency speech carefully.", DialogueCategory.NavigationGuidance),
        d("nav_07", "We will practice the action without triggering a real emergency alert.", DialogueCategory.EmergencyTrainingGuidance),
        // Practice
        d("prac_01", "Welcome back to practice.", DialogueCategory.Practice),
        d("prac_02", "We can practice at your pace.", DialogueCategory.Practice),
        d("prac_03", "Ready to practice together?", DialogueCategory.Practice),
        d("prac_04", "Let's repeat this until it feels comfortable.", DialogueCategory.Practice),
        d("prac_05", "You can stop whenever you need.", DialogueCategory.Practice),
        d("prac_06", "Practice helps Lisa understand your movements better.", DialogueCategory.Practice),
        // Minor celebration
        d("cel_minor_01", "Nice work.", DialogueCategory.MinorCelebration),
        d("cel_minor_02", "Great job.", DialogueCategory.MinorCelebration),
        d("cel_minor_03", "Excellent.", DialogueCategory.MinorCelebration),
        d("cel_minor_04", "You did it.", DialogueCategory.MinorCelebration),
        // Major celebration / lesson complete
        d("cel_lesson_01", "Wonderful.", DialogueCategory.MajorCelebration, milestone = MilestoneType.LessonComplete),
        d("cel_lesson_02", "You completed this lesson.", DialogueCategory.MajorCelebration, milestone = MilestoneType.LessonComplete),
        d("cel_lesson_03", "You're making real progress.", DialogueCategory.MajorCelebration, milestone = MilestoneType.LessonComplete),
        d("cel_lesson_04", "Let's keep going when you're ready.", DialogueCategory.MajorCelebration, milestone = MilestoneType.LessonComplete),
        // Milestone
        d("mil_first_blink", "That was your first successful blink with Lisa. Well done.", DialogueCategory.MilestoneCelebration, milestone = MilestoneType.FirstSuccessfulBlink),
        d("mil_first_phrase", "You just communicated using your eyes. That was wonderful.", DialogueCategory.MilestoneCelebration, milestone = MilestoneType.FirstSpokenPhrase),
        d("mil_comm_done", "You've learned the basic communication phrases. That is a meaningful step.", DialogueCategory.MilestoneCelebration, milestone = MilestoneType.CommunicationTrainingComplete),
        d("mil_nav_done", "You now know how to move around Lisa. That's excellent progress.", DialogueCategory.MilestoneCelebration, milestone = MilestoneType.NavigationTrainingComplete),
        d("mil_amazing", "That was amazing.", DialogueCategory.MilestoneCelebration),
        d("mil_independent", "You just communicated independently.", DialogueCategory.MilestoneCelebration),
        d("mil_important", "That was an important step.", DialogueCategory.MilestoneCelebration),
        // Graduation
        d("grad_01", "Congratulations.", DialogueCategory.Graduation, milestone = MilestoneType.GuidedLearningComplete),
        d("grad_02", "You now know how to communicate with me.", DialogueCategory.Graduation, milestone = MilestoneType.GuidedLearningComplete),
        d("grad_03", "You've done an amazing job.", DialogueCategory.Graduation, milestone = MilestoneType.GuidedLearningComplete),
        d("grad_04", "I'll always be here whenever you need me.", DialogueCategory.Graduation, milestone = MilestoneType.GuidedLearningComplete),
        d("grad_05", "You have worked through every step.", DialogueCategory.Graduation, milestone = MilestoneType.GuidedLearningComplete),
        d("grad_06", "You should feel proud of your progress.", DialogueCategory.Graduation, milestone = MilestoneType.GuidedLearningComplete),
        // Session completion
        d("sess_01", "Let's continue when you're ready.", DialogueCategory.SessionCompletion),
        d("sess_02", "We can pick this up again whenever you'd like.", DialogueCategory.SessionCompletion),
        // Return
        d("ret_01", "Welcome back.", DialogueCategory.ReturnMessage, milestone = MilestoneType.ReturningUser),
        d("ret_02", "We can continue gently from where you left off.", DialogueCategory.ReturnMessage, milestone = MilestoneType.ReturningUser),
        // Settings / sensitivity / recalibration
        d("set_01", "You can adjust these settings whenever you need.", DialogueCategory.SettingsGuidance),
        d("sens_01", "We can reduce blink sensitivity to make this easier.", DialogueCategory.SensitivityGuidance),
        d("a11y_easier", "Let's make this a little easier.", DialogueCategory.SettingsGuidance),
        d("a11y_text_size", "You can increase the text size in Settings.", DialogueCategory.SettingsGuidance),
        d("a11y_slow_down", "We can slow things down together.", DialogueCategory.Instruction),
        d("a11y_repeat_lesson", "Would you like to repeat this lesson?", DialogueCategory.Practice),
        d("recal_ok", "Your calibration looks good.", DialogueCategory.RecalibrationGuidance),
        d("recal_monitor", "I'll keep an eye on calibration quality while we communicate.", DialogueCategory.RecalibrationGuidance),
        d("recal_retry", "Let's try calibrating again together.", DialogueCategory.RecalibrationGuidance),
        d("recal_required", "We should calibrate before communicating.", DialogueCategory.RecalibrationGuidance),
        d("recal_invalid", "I think we can get a better result. Let's calibrate again.", DialogueCategory.RecalibrationGuidance),
        d("recal_encourage", "Take your time. We'll improve the calibration one step at a time.", DialogueCategory.RecalibrationGuidance),
        // Learning Journey V1 — stage dialogue (Personality Engine)
        d("jcal_01", "I'll show you a few dots.", DialogueCategory.Instruction, tags = setOf("journey_calibration_intro")),
        d("jcal_02", "Simply look at each one.", DialogueCategory.Instruction, tags = setOf("journey_calibration_intro")),
        d("jcal_03", "Fantastic.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_calibration_excellent")),
        d("jcal_04", "I can see your eyes clearly.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_calibration_excellent")),
        d("jcal_05", "Great.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_calibration_acceptable")),
        d("jcal_06", "We can improve this later if we need to.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_calibration_acceptable")),
        d("jcal_07", "That's alright.", DialogueCategory.Comfort, tags = setOf("journey_calibration_poor")),
        d("jcal_08", "I think we can do even better.", DialogueCategory.Comfort, tags = setOf("journey_calibration_poor")),
        d("jcal_09", "Let's try once more together.", DialogueCategory.Comfort, tags = setOf("journey_calibration_poor")),
        d("jfund_01", "Wonderful.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_fundamentals_complete")),
        d("jfund_02", "You've learned your first communication phrases.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_fundamentals_complete")),
        d("jfund_03", "You can already express many important thoughts.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_fundamentals_complete")),
        d("jfund_04", "We're making wonderful progress together.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_fundamentals_complete")),
        d("jmast_01", "Now let's practice together.", DialogueCategory.Instruction, tags = setOf("journey_mastery_intro")),
        d("jmast_02", "I'll ask you for phrases in different orders.", DialogueCategory.Instruction, tags = setOf("journey_mastery_intro")),
        d("jmast_03", "Take your time.", DialogueCategory.Instruction, tags = setOf("journey_mastery_intro")),
        d("jmast_04", "You've learned how to communicate.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_mastery_complete")),
        d("jmast_05", "Now I'd like to teach you how to use the rest of Lisa.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_mastery_complete")),
        d("jws_01", "Now I'd like to teach you how to move around Lisa using your eyes.", DialogueCategory.NavigationGuidance, tags = setOf("journey_workspace_intro")),
        d("jws_02", "These are your communication categories.", DialogueCategory.NavigationGuidance, tags = setOf("journey_workspace_intro")),
        d("jws_03", "You now know how to use your communication workspace.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_workspace_complete")),
        d("jws_04", "This is where you'll communicate every day.", DialogueCategory.MilestoneCelebration, tags = setOf("journey_workspace_complete")),
        d("jcert_01", "Congratulations.", DialogueCategory.Graduation, tags = setOf("journey_certification"), milestone = MilestoneType.GuidedLearningComplete),
        d("jcert_02", "You've completed your first communication journey.", DialogueCategory.Graduation, tags = setOf("journey_certification")),
        d("jcert_03", "You've learned how to communicate using your eyes.", DialogueCategory.Graduation, tags = setOf("journey_certification")),
        d("jcert_04", "From today, this becomes your communication workspace.", DialogueCategory.Graduation, tags = setOf("journey_certification")),
        d("jcert_05", "You are now a LISA Certified Communicator.", DialogueCategory.Graduation, tags = setOf("journey_certification")),
        d("jcert_06", "I'll always be here whenever you need me.", DialogueCategory.Graduation, tags = setOf("journey_certification")),
        d("gls_ws_01", "You now know the basics.", DialogueCategory.Graduation, tags = setOf("gl_simplify_workspace_transition")),
        d("gls_ws_02", "You're ready to begin communicating.", DialogueCategory.Graduation, tags = setOf("gl_simplify_workspace_transition")),
        d("gls_ws_03", "Let's go to Communication.", DialogueCategory.Graduation, tags = setOf("gl_simplify_workspace_transition")),
        d("jnav_cat", "These are your communication categories.", DialogueCategory.NavigationGuidance, tags = setOf("nav_categories")),
        d("jnav_open", "Let's open Medical.", DialogueCategory.NavigationGuidance, tags = setOf("nav_open_category")),
        d("jnav_return", "Let's return to the categories.", DialogueCategory.NavigationGuidance, tags = setOf("nav_return")),
        d("jnav_repeat", "Let's practice Repeat.", DialogueCategory.NavigationGuidance, tags = setOf("nav_repeat")),
        d("jnav_menu", "Let's open the menu.", DialogueCategory.NavigationGuidance, tags = setOf("nav_menu")),
        d("jnav_history", "This is your communication history.", DialogueCategory.NavigationGuidance, tags = setOf("nav_history")),
        d("jnav_reset", "Clear removes your current message when you need a fresh start.", DialogueCategory.NavigationGuidance, tags = setOf("nav_reset")),
        d("jnav_emerg", "This option is only for emergencies.", DialogueCategory.EmergencyTrainingGuidance, tags = setOf("nav_emergency")),
        d("jnav_emerg2", "We'll practice it safely together.", DialogueCategory.EmergencyTrainingGuidance, tags = setOf("nav_emergency")),
        // Brain 1 Interaction Standard — decision confirmation dialogue
        d("b1_fl_01", "Would you like to begin Guided Learning...", DialogueCategory.Instruction, tags = setOf("b1_first_launch")),
        d("b1_fl_02", "...or go directly to Communication?", DialogueCategory.Instruction, tags = setOf("b1_first_launch")),
        d("b1_fl_03", "Blink Left twice to begin learning.", DialogueCategory.Instruction, tags = setOf("b1_first_launch")),
        d("b1_fl_04", "Blink Right twice to skip to Communication.", DialogueCategory.Instruction, tags = setOf("b1_first_launch")),
        d("b1_rep_01", "I think you chose {choice}.", DialogueCategory.Instruction, tags = setOf("b1_repeat_choice")),
        d("b1_rep_02", "If that's correct...", DialogueCategory.Instruction, tags = setOf("b1_repeat_choice")),
        d("b1_con_01", "Blink Left then Right to continue.", DialogueCategory.Instruction, tags = setOf("b1_confirm")),
        d("b1_con_02", "L1 R1 to continue.", DialogueCategory.Instruction, tags = setOf("b1_confirm")),
        d("b1_ch_01", "If you'd like to choose again...", DialogueCategory.Instruction, tags = setOf("b1_choose_again")),
        d("b1_ch_02", "Blink Right then Left.", DialogueCategory.Instruction, tags = setOf("b1_choose_again")),
        d("b1_ch_03", "R1 L1 to choose again.", DialogueCategory.Instruction, tags = setOf("b1_choose_again")),
        d("b1_sk_01", "Guided Learning is recommended for first-time users.", DialogueCategory.Instruction, tags = setOf("b1_skip_warning")),
        d("b1_em_01", "I believe you want to enter Emergency Mode.", DialogueCategory.EmergencyTrainingGuidance, tags = setOf("b1_emergency_repeat")),
        d("b1_em_02", "If that's correct, blink Left then Right.", DialogueCategory.EmergencyTrainingGuidance, tags = setOf("b1_emergency_repeat")),
        d("b1_em_03", "If not, blink Right then Left.", DialogueCategory.EmergencyTrainingGuidance, tags = setOf("b1_emergency_repeat")),
        d("b1_rs_01", "I believe you'd like to reset your learning progress.", DialogueCategory.Instruction, tags = setOf("b1_reset_repeat")),
        d("b1_rs_02", "Your progress will be lost.", DialogueCategory.Instruction, tags = setOf("b1_reset_repeat")),
        d("b1_rc_01", "I think recalibration will help us communicate more accurately.", DialogueCategory.RecalibrationGuidance, tags = setOf("b1_recal_prompt")),
        d("b1_rc_02", "Would you like to recalibrate?", DialogueCategory.RecalibrationGuidance, tags = setOf("b1_recal_prompt")),
        d("b1_ci_01", "Wonderful.", DialogueCategory.MilestoneCelebration, tags = setOf("b1_cal_intro")),
        d("b1_ci_02", "Before we begin communicating...", DialogueCategory.Instruction, tags = setOf("b1_cal_intro")),
        d("b1_ci_03", "I'd like to learn how your eyes move.", DialogueCategory.Instruction, tags = setOf("b1_cal_intro")),
        d("b1_cd_01", "Please look at the blue dot.", DialogueCategory.Instruction, tags = setOf("b1_cal_dot")),
        d("b1_cd_02", "Now let's look at the next one.", DialogueCategory.Instruction, tags = setOf("b1_cal_dot")),
        d("b1_cs_01", "Wonderful.", DialogueCategory.MilestoneCelebration, tags = setOf("b1_cal_success")),
        d("b1_cs_02", "Now let's look at the next one.", DialogueCategory.MilestoneCelebration, tags = setOf("b1_cal_success")),
        // Phase A — First Five Minutes polish
        d("pa_ml_01", "Hello.", DialogueCategory.Greeting, tags = setOf("phase_a_meet_lisa")),
        d("pa_ml_02", "My name is Lisa.", DialogueCategory.Greeting, tags = setOf("phase_a_meet_lisa")),
        d("pa_ml_03", "I'm here to help you communicate using your eyes.", DialogueCategory.Greeting, tags = setOf("phase_a_meet_lisa")),
        d("pa_ml_04", "If you cannot move your hands, that's perfectly okay.", DialogueCategory.Greeting, tags = setOf("phase_a_meet_lisa")),
        d("pa_ml_05", "Everything we're going to do can be done using only your eyes.", DialogueCategory.Greeting, tags = setOf("phase_a_meet_lisa")),
        d("pa_ml_06", "I'll guide you every step of the way.", DialogueCategory.Greeting, tags = setOf("phase_a_meet_lisa")),
        d("pa_ml_07", "There is no rush.", DialogueCategory.Greeting, tags = setOf("phase_a_meet_lisa")),
        d("pa_ml_08", "We'll learn together.", DialogueCategory.Greeting, tags = setOf("phase_a_meet_lisa")),
        d("pa_gr_01", "Before we begin, I'd like to make sure I can see you clearly.", DialogueCategory.Instruction, tags = setOf("phase_a_getting_ready")),
        d("pa_gr_02", "I'm looking for your face.", DialogueCategory.Instruction, tags = setOf("phase_a_getting_ready")),
        d("pa_fd_01", "Wonderful.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_face_detected")),
        d("pa_fd_02", "I can see you now.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_face_detected")),
        d("pa_fl_01", "I've lost sight of you.", DialogueCategory.Comfort, tags = setOf("phase_a_face_lost")),
        d("pa_fl_02", "When you're ready, simply look back at me.", DialogueCategory.Comfort, tags = setOf("phase_a_face_lost")),
        d("pa_fw_01", "I'll wait until I can see you.", DialogueCategory.Comfort, tags = setOf("phase_a_face_waiting")),
        d("pa_fw_02", "Try to keep your face gently facing the phone.", DialogueCategory.Comfort, tags = setOf("phase_a_face_waiting")),
        d("pa_ci_01", "Wonderful.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_cal_intro")),
        d("pa_ci_02", "Before we begin communicating...", DialogueCategory.Instruction, tags = setOf("phase_a_cal_intro")),
        d("pa_ci_03", "I'd like to learn how your eyes move.", DialogueCategory.Instruction, tags = setOf("phase_a_cal_intro")),
        d("pa_ci_04", "I'll show you a few dots.", DialogueCategory.Instruction, tags = setOf("phase_a_cal_intro")),
        d("pa_ci_05", "Simply look at each one.", DialogueCategory.Instruction, tags = setOf("phase_a_cal_intro")),
        d("pa_cd_01", "Please look at the blue dot.", DialogueCategory.Instruction, tags = setOf("phase_a_cal_dot")),
        d("pa_cc_01", "Great.", DialogueCategory.Encouragement, tags = setOf("phase_a_cal_captured")),
        d("pa_cc_02", "Now let's look at the next one.", DialogueCategory.Encouragement, tags = setOf("phase_a_cal_captured")),
        d("pa_cs_01", "That's okay.", DialogueCategory.Comfort, tags = setOf("phase_a_cal_struggle")),
        d("pa_cs_02", "Keep looking at the blue dot.", DialogueCategory.Comfort, tags = setOf("phase_a_cal_struggle")),
        d("pa_ce_01", "Fantastic.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_cal_excellent")),
        d("pa_ce_02", "I can see your eyes clearly.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_cal_excellent")),
        d("pa_ce_03", "We're ready.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_cal_excellent")),
        d("pa_ca_01", "Great.", DialogueCategory.Encouragement, tags = setOf("phase_a_cal_acceptable")),
        d("pa_ca_02", "We can improve this later if we need to.", DialogueCategory.Encouragement, tags = setOf("phase_a_cal_acceptable")),
        d("pa_cp_01", "That's alright.", DialogueCategory.Comfort, tags = setOf("phase_a_cal_poor")),
        d("pa_cp_02", "I think we can get a clearer result.", DialogueCategory.Comfort, tags = setOf("phase_a_cal_poor")),
        d("pa_cp_03", "Let's try once more together.", DialogueCategory.Comfort, tags = setOf("phase_a_cal_poor")),
        d("pa_fs_01", "Wonderful!", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_first_success")),
        d("pa_fs_02", "You did it!", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_first_success")),
        d("pa_fs_03", "You've just spoken your first word using Lisa.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_a_first_success")),
        d("pa_fe_01", "That was excellent.", DialogueCategory.Encouragement, tags = setOf("phase_a_first_encourage")),
        d("pa_fe_02", "Let's learn another one.", DialogueCategory.Encouragement, tags = setOf("phase_a_first_encourage")),
        d("pa_np_01", "Now let's learn how to say yes.", DialogueCategory.Instruction, tags = setOf("phase_a_next_phrase")),
        d("pa_gm_01", "I think I missed that blink.", DialogueCategory.Comfort, tags = setOf("phase_a_gentle_miss")),
        d("pa_gm_02", "Let's try once more together.", DialogueCategory.Comfort, tags = setOf("phase_a_gentle_miss")),
        d("pa_gm_03", "That's alright.", DialogueCategory.Comfort, tags = setOf("phase_a_gentle_miss")),
        d("pa_gm_04", "We'll keep trying together.", DialogueCategory.Comfort, tags = setOf("phase_a_gentle_miss")),
        d("pa_pt_01", "I'll wait until you're ready.", DialogueCategory.Comfort, tags = setOf("phase_a_patience")),
        d("pa_pt_02", "There's no rush.", DialogueCategory.Comfort, tags = setOf("phase_a_patience")),
        d("pa_pt_03", "We can take our time.", DialogueCategory.Comfort, tags = setOf("phase_a_patience")),
        // Phase B — Communication Workspace polish
        d("pb_we_01", "Welcome to Communication.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_b_workspace_entry")),
        d("pb_we_02", "This is where you'll communicate every day.", DialogueCategory.Instruction, tags = setOf("phase_b_workspace_entry")),
        d("pb_we_03", "Blink the sequence beside any phrase to speak it.", DialogueCategory.Instruction, tags = setOf("phase_b_workspace_entry")),
        d("pb_we_04", "Use L4 R4 to open your categories.", DialogueCategory.Instruction, tags = setOf("phase_b_workspace_entry")),
        d("pb_we_05", "I'll stay right here with you.", DialogueCategory.Comfort, tags = setOf("phase_b_workspace_entry")),
        d("pb_ni_01", "L2 and R2 scroll through phrases.", DialogueCategory.NavigationGuidance, tags = setOf("phase_b_nav_intro")),
        d("pb_ni_02", "L1 R1 selects the highlighted phrase.", DialogueCategory.NavigationGuidance, tags = setOf("phase_b_nav_intro")),
        d("pb_ni_03", "L2 R2 goes back.", DialogueCategory.NavigationGuidance, tags = setOf("phase_b_nav_intro")),
        d("pb_ca_01", "These are your communication categories.", DialogueCategory.NavigationGuidance, tags = setOf("phase_b_categories")),
        d("pb_ca_02", "Blink L2 or R2 to move.", DialogueCategory.NavigationGuidance, tags = setOf("phase_b_categories")),
        d("pb_ca_03", "Blink L1 R1 to open a category.", DialogueCategory.NavigationGuidance, tags = setOf("phase_b_categories")),
        d("pb_ps_01", "Blink the sequence beside a phrase to speak it.", DialogueCategory.Instruction, tags = setOf("phase_b_phrase_select")),
        d("pb_ps_02", "Take your time.", DialogueCategory.Comfort, tags = setOf("phase_b_phrase_select")),
        d("pb_bk_01", "L2 R2 always takes you back one step.", DialogueCategory.NavigationGuidance, tags = setOf("phase_b_back")),
        d("pb_bk_02", "From categories, L2 R2 returns to phrases.", DialogueCategory.NavigationGuidance, tags = setOf("phase_b_back")),
        d("pb_em_01", "Emergency is L6 R0.", DialogueCategory.EmergencyTrainingGuidance, tags = setOf("phase_b_emergency")),
        d("pb_em_02", "Lisa will ask you to confirm before activating.", DialogueCategory.EmergencyTrainingGuidance, tags = setOf("phase_b_emergency")),
        d("pb_cg_01", "Caregiver help: gestures are shown beside each action.", DialogueCategory.Instruction, tags = setOf("phase_b_caregiver_help")),
        d("pb_cg_02", "L2 R0 up · L0 R2 down · L1 R1 select · L2 R2 back · L4 R4 categories · L6 R0 emergency.", DialogueCategory.Instruction, tags = setOf("phase_b_caregiver_help")),
        d("pb_pt_01", "There's no rush.", DialogueCategory.Comfort, tags = setOf("phase_b_patience")),
        d("pb_pt_02", "I'll wait until you're ready.", DialogueCategory.Comfort, tags = setOf("phase_b_patience")),
        d("pb_hv_01", "Blink a phrase sequence to speak it · L4 R4 for categories", DialogueCategory.Instruction, tags = setOf("phase_b_hint_vocab")),
        d("pb_hc_01", "L2/R2 move · L1 R1 open category · L2 R2 back to phrases", DialogueCategory.Instruction, tags = setOf("phase_b_hint_categories")),
        d("pb_ha_01", "L3 R1 decrease · L1 R3 increase · L1 R1 save · L2 R2 back", DialogueCategory.Instruction, tags = setOf("phase_b_hint_adjust")),
        // Patient Communication Coach — guided learning pacing
        d("pc_ph_01", "Let's learn this phrase together.", DialogueCategory.Instruction, tags = setOf("phase_c_coach_phrase")),
        d("pc_ph_02", "This is a useful everyday phrase.", DialogueCategory.Instruction, tags = setOf("phase_c_coach_phrase")),
        d("pc_ph_03", "Take your time with the blink sequence.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_phrase")),
        d("pc_rp_01", "Let's try that phrase once more together.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_repeat")),
        d("pc_rp_02", "I'll say it again with you.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_repeat")),
        d("pc_sl_01", "I'll slow down and wait with you.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_slow")),
        d("pc_sl_02", "No rush — we can take another moment.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_slow")),
        d("pc_br_01", "This one adds one more blink.", DialogueCategory.Instruction, tags = setOf("phase_c_coach_bridge")),
        d("pc_br_02", "We'll take this step slowly.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_bridge")),
        d("pc_br_03", "Same calm pace — just one extra blink.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_bridge")),
        d("pc_rs_01", "You've done several phrases — a short pause is fine.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_rest")),
        d("pc_rs_02", "I'll wait whenever you need a moment.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_rest")),
        d("pc_pt_01", "There's no rush.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_patience")),
        d("pc_pt_02", "I'll wait until you're ready.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_patience")),
        d("pc_pt_03", "We can try again when you feel ready.", DialogueCategory.Comfort, tags = setOf("phase_c_coach_patience")),
        d("pc_cm_01", "Well done.", DialogueCategory.Encouragement, tags = setOf("phase_c_coach_celebrate_minor")),
        d("pc_cm_02", "That was clear.", DialogueCategory.Encouragement, tags = setOf("phase_c_coach_celebrate_minor")),
        d("pc_cl_01", "You've mastered this level.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_c_coach_celebrate_level")),
        d("pc_cl_02", "Beautiful progress — ready for the next phrase.", DialogueCategory.MilestoneCelebration, tags = setOf("phase_c_coach_celebrate_level")),
        // Emotional Presence V1 — warm, brief, observable (no fake intelligence)
        d("ep_so_01", "I'm here when you're ready.", DialogueCategory.Welcome, tags = setOf("presence_session_open")),
        d("ep_so_02", "Let's take today one phrase at a time.", DialogueCategory.Welcome, tags = setOf("presence_session_open")),
        d("ep_so_03", "Good to see you.", DialogueCategory.Welcome, tags = setOf("presence_session_open")),
        d("ep_wr_01", "Welcome back — we can pick up gently.", DialogueCategory.ReturnMessage, tags = setOf("presence_return_warm"), milestone = MilestoneType.ReturningUser),
        d("ep_wr_02", "I'm glad you're here again.", DialogueCategory.ReturnMessage, tags = setOf("presence_return_warm"), milestone = MilestoneType.ReturningUser),
        d("ep_wr_03", "We can continue at your pace.", DialogueCategory.ReturnMessage, tags = setOf("presence_return_warm"), milestone = MilestoneType.ReturningUser),
        d("ep_lp_01", "Take your time — I'm still here.", DialogueCategory.Waiting, tags = setOf("presence_long_pause")),
        d("ep_lp_02", "No rush. I'll wait with you.", DialogueCategory.Waiting, tags = setOf("presence_long_pause")),
        d("ep_lp_03", "Whenever you're ready, we can continue.", DialogueCategory.Waiting, tags = setOf("presence_long_pause")),
        d("ep_cg_01", "Caregiver: Lisa waits patiently — no timer pressure.", DialogueCategory.Comfort, tags = setOf("presence_caregiver_reassure")),
        d("ep_cg_02", "Caregiver: progress is saved; breaks are welcome.", DialogueCategory.Comfort, tags = setOf("presence_caregiver_reassure")),
        d("ep_cg_03", "Caregiver: one phrase at a time is enough.", DialogueCategory.Comfort, tags = setOf("presence_caregiver_reassure")),
        d("ep_ft_01", "A short rest is fine.", DialogueCategory.Comfort, tags = setOf("presence_fatigue_checkin")),
        d("ep_ft_02", "We can pause here and come back when you're ready.", DialogueCategory.Comfort, tags = setOf("presence_fatigue_checkin")),
        d("ep_ft_03", "You've done plenty for now.", DialogueCategory.Comfort, tags = setOf("presence_fatigue_checkin")),
        d("ep_ms_01", "That was a meaningful step.", DialogueCategory.MilestoneCelebration, tags = setOf("presence_emotional_milestone")),
        d("ep_ms_02", "You should feel proud of that.", DialogueCategory.MilestoneCelebration, tags = setOf("presence_emotional_milestone")),
        d("ep_ms_03", "What you just did matters.", DialogueCategory.MilestoneCelebration, tags = setOf("presence_emotional_milestone")),
        // Caregiver Confidence V1 — plain, actionable, caregiver-facing
        d("cc_pp_01", "Caregiver: hold the phone steady at eye level, about an arm's length away.", DialogueCategory.SettingsGuidance, tags = setOf("cg_phone_position")),
        d("cc_pp_02", "Caregiver: tilt the screen so the camera sees the whole face comfortably.", DialogueCategory.SettingsGuidance, tags = setOf("cg_phone_position")),
        d("cc_pp_03", "Caregiver: a small stand or pillow can keep the phone from moving.", DialogueCategory.SettingsGuidance, tags = setOf("cg_phone_position")),
        d("cc_cl_01", "Caregiver: face a window or lamp — soft, even light works best.", DialogueCategory.SettingsGuidance, tags = setOf("cg_camera_lighting")),
        d("cc_cl_02", "Caregiver: avoid bright light behind the user; it can hide their eyes.", DialogueCategory.SettingsGuidance, tags = setOf("cg_camera_lighting")),
        d("cc_cl_03", "Caregiver: if the room is dim, add light in front of the face, not behind.", DialogueCategory.SettingsGuidance, tags = setOf("cg_camera_lighting")),
        d("cc_cs_01", "Caregiver: help them look at each blue dot — no rush.", DialogueCategory.RecalibrationGuidance, tags = setOf("cg_calibration_support")),
        d("cc_cs_02", "Caregiver: stay still while Lisa learns their eye position.", DialogueCategory.RecalibrationGuidance, tags = setOf("cg_calibration_support")),
        d("cc_cs_03", "Caregiver: if a dot is missed, Lisa will gently try again.", DialogueCategory.RecalibrationGuidance, tags = setOf("cg_calibration_support")),
        d("cc_cs_04", "Caregiver: poor calibration? Check lighting and phone steadiness, then retry.", DialogueCategory.RecalibrationGuidance, tags = setOf("cg_calibration_support")),
        d("cc_hi_01", "Caregiver: Lisa guides with eyes — you can help with setup and encouragement.", DialogueCategory.Instruction, tags = setOf("cg_caregiver_hint")),
        d("cc_hi_02", "Caregiver: practice together before relying on Lisa alone.", DialogueCategory.Instruction, tags = setOf("cg_caregiver_hint")),
        d("cc_hi_03", "Caregiver: gestures are shown beside each action on screen.", DialogueCategory.Instruction, tags = setOf("cg_caregiver_hint")),
        d("cc_ts_01", "Caregiver: if blinks are missed, try lowering sensitivity one step.", DialogueCategory.SensitivityGuidance, tags = setOf("cg_troubleshooting")),
        d("cc_ts_02", "Caregiver: if blinks trigger too easily, raise sensitivity one step.", DialogueCategory.SensitivityGuidance, tags = setOf("cg_troubleshooting")),
        d("cc_ts_03", "Caregiver: recalibrate from the menu if tracking feels off.", DialogueCategory.RecalibrationGuidance, tags = setOf("cg_troubleshooting")),
        d("cc_ts_04", "Caregiver: wipe the front camera lens if the image looks blurry.", DialogueCategory.SettingsGuidance, tags = setOf("cg_troubleshooting")),
        d("cc_pv_01", "Caregiver: progress is saved automatically.", DialogueCategory.Instruction, tags = setOf("cg_progress_visibility")),
        d("cc_pv_02", "Caregiver: lesson count and successes are shown below.", DialogueCategory.Instruction, tags = setOf("cg_progress_visibility")),
        d("cc_pv_03", "Caregiver: short breaks are normal — Lisa waits patiently.", DialogueCategory.Comfort, tags = setOf("cg_progress_visibility")),
        d("cc_tr_01", "Caregiver: bring the face back into view — Lisa will resume listening.", DialogueCategory.Comfort, tags = setOf("cg_tracking_recovery")),
        d("cc_tr_02", "Caregiver: check that nothing is blocking the camera.", DialogueCategory.Comfort, tags = setOf("cg_tracking_recovery")),
        d("cc_tr_03", "Caregiver: gently reposition the phone if the face left the frame.", DialogueCategory.Comfort, tags = setOf("cg_tracking_recovery")),
        d("cc_wd_01", "Caregiver: tap Allow Camera when prompted.", DialogueCategory.Instruction, tags = setOf("cg_what_to_do_now")),
        d("cc_wd_02", "Caregiver: read the safety note, then tap Continue.", DialogueCategory.Instruction, tags = setOf("cg_what_to_do_now")),
        d("cc_wd_03", "Caregiver: enter the user's name, then tap Continue.", DialogueCategory.Instruction, tags = setOf("cg_what_to_do_now")),
        d("cc_wd_04", "Caregiver: wait for Lisa to finish speaking, then try the blink sequence.", DialogueCategory.Instruction, tags = setOf("cg_what_to_do_now")),
        d("cc_wd_05", "Caregiver: if stuck, open Settings → adjust sensitivity or recalibrate.", DialogueCategory.Instruction, tags = setOf("cg_what_to_do_now"))
    )
}
